# Generated by Django 4.0.4 on 2022-06-01 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simsonet_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='name',
            field=models.CharField(db_index=True, default='Personal', max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='wall',
            unique_together={('owner', 'name')},
        ),
    ]
