# Generated by Django 4.0.4 on 2022-06-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simsonet_posts', '0003_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='simsonet_posts.post', verbose_name='reply to'),
        ),
        migrations.AlterField(
            model_name='post',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='simsonet_posts.post', verbose_name='repost of'),
        ),
    ]
